# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a5c4a29a3f7153a4b2e49b4df38cb8f9d68ddea6550eaf5f7ffd3845ae0f630f52df826c6fa7258ed2fe0f9d38c89d6d31cd6037b9481ff5d5aefe3bf857881

test:
  secret_key_base: b37caca5b6a8586e67a4dd183b698e2c188a6b554d36b15b158d36c5411cf3edf974e080380ae17786a6a60dc2b30ec5c6305e9e51316baeeef5091b86213ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
